# lightning.pytorch==2.1.1
custom_modules_path: "/home/sagemaker-user/ESA-NASA-workshop-2025/Track 3 (Benchmarking)/GEO-Bench-demo/tiny_backbone"
seed_everything: 42
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed
  logger: True

  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: epoch
  max_epochs: 5
  log_every_n_steps: 5
  default_root_dir: ./logs/

data:
  class_path: terratorch.datamodules.GenericNonGeoSegmentationDataModule
  init_args:
    batch_size: 4
    num_workers: 4
    constant_scale: 0.0001
    dataset_bands:
      - COASTAL_AEROSOL
      - BLUE
      - GREEN
      - RED
      - RED_EDGE_1
      - RED_EDGE_2
      - RED_EDGE_3
      - NIR_BROAD
      - NIR_NARROW
      - CIRRUS
      - SWIR_1
      - SWIR_2
    output_bands:
     - BLUE
     - GREEN
     - RED
     - NIR_NARROW
     - SWIR_1
     - SWIR_2
    rgb_indices:
      - 2
      - 1
      - 0
    train_data_root: "/home/sagemaker-user/ESA-NASA-workshop-2025/Track 3 (Benchmarking)/GEO-Bench-demo/datasets/sen1flloods11/S2L2AHand"
    train_label_data_root: "/home/sagemaker-user/ESA-NASA-workshop-2025/Track 3 (Benchmarking)/GEO-Bench-demo/datasets/sen1flloods11/LabelHand"
    val_data_root: "/home/sagemaker-user/ESA-NASA-workshop-2025/Track 3 (Benchmarking)/GEO-Bench-demo/datasets/sen1flloods11/S2L2AHand"
    val_label_data_root: "/home/sagemaker-user/ESA-NASA-workshop-2025/Track 3 (Benchmarking)/GEO-Bench-demo/datasets/sen1flloods11/LabelHand"
    test_data_root: "/home/sagemaker-user/ESA-NASA-workshop-2025/Track 3 (Benchmarking)/GEO-Bench-demo/datasets/sen1flloods11/S2L2AHand"
    test_label_data_root: "/home/sagemaker-user/ESA-NASA-workshop-2025/Track 3 (Benchmarking)/GEO-Bench-demo/datasets/sen1flloods11/LabelHand"
    train_split: "/home/sagemaker-user/ESA-NASA-workshop-2025/Track 3 (Benchmarking)/GEO-Bench-demo/datasets/sen1flloods11/splits/flood_handlabeled/flood_train_data.txt"
    val_split: "/home/sagemaker-user/ESA-NASA-workshop-2025/Track 3 (Benchmarking)/GEO-Bench-demo/datasets/sen1flloods11/splits/flood_handlabeled/flood_valid_data.txt"
    test_split: "/home/sagemaker-user/ESA-NASA-workshop-2025/Track 3 (Benchmarking)/GEO-Bench-demo/datasets/sen1flloods11/splits/flood_handlabeled/flood_test_data.txt"
    check_stackability: false
    img_grep: "*_S2L2AHand.tif"
    label_grep: "*_LabelHand.tif"
    no_label_replace: -1
    no_data_replace: 0
    means:
      - 0.11076498225107874
      - 0.13456047562676646
      - 0.12477149645635542
      - 0.3248933937526503
      - 0.23118412840904512
      - 0.15624583324071273
    stds:
      - 0.15469174852002912
      - 0.13070592427323752
      - 0.12786689586224442
      - 0.13925781946803198
      - 0.11303782829438778
      - 0.10207461132314981
    num_classes: 2
    drop_last: True
    train_transform:
      - class_path: albumentations.D4
      - class_path: albumentations.pytorch.ToTensorV2

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    tiled_inference_parameters:
      h_crop: 512
      h_stride: 512
      w_crop: 512
      w_stride: 512
      average_patches: true
    model_factory: EncoderDecoderFactory
    model_args:
      backbone: tiny_backbone
      backbone_pretrained: false
      backbone_in_channels: 6
      decoder: IdentityDecoder
      num_classes: 2
      head_dropout: 0.1
      head_channel_list:
        - 256
    loss: dice
    ignore_index: -1
    freeze_backbone: false
    freeze_decoder: false
    plot_on_val: 0
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.e-4
    weight_decay: 0.1
lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val/loss
    factor: 0.5
    patience: 10
